class AppData
  include MongoMapper::Document
  # NOTE: Be careful not to override id or _id keys
  # that are pregenerated by Rails and result with
  #unexpected behaviour such as stack errors
  
  scope :search,      lambda { |query| where(query) }
  
  # app_id is float to avoid overflows
  key :a_id,          Float,    :required => true 
  key :bundle_id,     String,   :required => true
  key :name,          String,   :required => true
  key :summary,       String,   :required => true
  key :devices,       Array,    :required => true
  key :advisory,      String,   :required => true
  key :game_center,   Boolean
  key :size,          Integer,  :required => true
  key :lang,          Array,    :required => true
  key :version,       String,   :required => true
  
  one :publisher, :autosave => false
  one :pics,      :autosave => false
  many :store,    :autosave => false
  
  timestamps!
  
  # Validating game_center boolean flag since required false
  # acts according to Object#blank and will not work
  validates_inclusion_of :game_center, :in => [true, false]

end
