class Pics
  include MongoMapper::EmbeddedDocument
  # NOTE: Be careful not to override id or _id keys
  # that are pregenerated by Rails and result with
  #unexpected behaviour such as stack errors

  key :iphone,      Array,  :required => true
  key :ipad,        Array
  key :icon60,      String,  :required => true
  key :icon100,     String,  :required => true
  key :icon512,     String,  :required => true
  
  timestamps!

end
