class Price
  include MongoMapper::EmbeddedDocument
  # NOTE: Be careful not to override id or _id keys
  # that are pregenerated by Rails and result with
  #unexpected behaviour such as stack errors
  
  key :amount,      Float,    :required => true
  key :currency,    String,   :required => true
  
  timestamps!

end
