class Publisher
  include MongoMapper::EmbeddedDocument
  # NOTE: Be careful not to override id or _id keys
  # that are pregenerated by Rails and result with
  #unexpected behaviour such as stack errors
  
  # Publisher id is float in order to avoid overflow
  key :p_id,        Float,    :required => true
  key :name,      String,     :required => true
  key :company,   String,     :required => true
  
  timestamps!

end
