class Rank
  include MongoMapper::EmbeddedDocument
  # NOTE: Be careful not to override id, _id, name keys
  # that are pregenerated by Rails and result with
  #unexpected behaviour such as stack errors
  
  key :new_apps,                  Integer
  key :new_free_apps,             Integer
  key :new_paid_apps,             Integer

  key :top_free_apps_iphone,      Integer
  key :top_paid_apps_iphone,      Integer
  key :top_gros_apps_iphone,      Integer
  
  key :top_free_apps_ipad,        Integer
  key :top_paid_apps_ipad,        Integer
  key :top_gros_apps_ipad,        Integer
  
  timestamps!

end
