class Rank
  include MongoMapper::EmbeddedDocument
  # NOTE: Be careful not to override id, _id, name keys
  # that are pregenerated by Rails and result with
  #unexpected behaviour such as stack errors
  
  key :new_rank,                  String
  key :new_free_rank,             String
  key :new_paid_rank,             String

  key :iphone_top_free_rank,      String
  key :iphone_top_paid_rank,      String
  key :iphone_top_grossing_rank,  String
  
  key :ipad_top_free_rank,        String
  key :ipad_top_paid_rank,        String
  key :ipad_top_grossing_rank,    String
  
  timestamps!

end
