class Review
  include MongoMapper::EmbeddedDocument
  # NOTE: Be careful not to override id or _id keys
  # that are pregenerated by Rails and result with
  #unexpected behaviour such as stack errors
  
  key :version,   String,   :required => true
  key :rating,    Integer,  :required => true
  key :author,    String,   :required => true
  key :date,      Date,     :required => true
  key :subject,   String,   :required => true
  key :body,      String,   :required => true
  
  timestamps!

end
