class Store
  include MongoMapper::EmbeddedDocument
  # NOTE: Be careful not to override id or _id keys
  # that are pregenerated by Rails and result with
  #unexpected behaviour such as stack errors
  
  key :country,             String,   :required => true
  key :release_date,        Time,     :required => true
  key :link,                String,   :required => true
  key :p_link,              String,   :required => true
  
  key :total_ratings_count,  Integer
  key :total_average_rating, Float
  key :current_ratings_count,  Integer
  key :current_average_rating, Float
  
  one :rank
  one :price 
  many :review
  
  timestamps!

end
